name: 'GitHub Actions Security Checker'
description: 'Checks GitHub Actions for security best practices: verified publishers and commit hash pinning'
author: 'Twin Sun LLC'
branding:
  icon: 'shield'
  color: 'green'
inputs:
  github_token:
    description: 'GitHub token for API access to check verified publishers'
    required: true
    default: ${{ github.token }}
  workflows_dir:
    description: 'Directory containing workflow files to audit'
    required: false
    default: '.github/workflows'
outputs:
  report:
    description: 'Security audit report in Markdown format'
    value: ${{ steps.audit.outputs.report }}
  exit_code:
    description: 'Exit code (0 for pass, 1 for fail)'
    value: ${{ steps.audit.outputs.exit_code }}
  passed:
    description: 'Boolean indicating if all checks passed'
    value: ${{ steps.audit.outputs.exit_code == '0' }}
runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml requests
    
    - name: Run security audit
      id: audit
      shell: bash
      run: |
        set -e
        
        # Copy the audit script to the working directory
        cp ${{ github.action_path }}/audit_actions.py ./audit_actions.py
        
        # Make script executable and run it
        chmod +x audit_actions.py
        python3 audit_actions.py
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        WORKFLOWS_DIR: ${{ inputs.workflows_dir }}