name: Allowlist Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # Should bypass publisher check but still require pinning (PASS)
      - uses: actions/setup-node@v4  # Allowlisted but not pinned (FAIL)
      - uses: some-vendor/action@abc123def456789012345678901234567890123456  # Not allowlisted, should fail publisher check (FAIL)