name: Mixed Actions Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/build-push-action@v5
      - uses: suspicious/action@v1
      - uses: hashicorp/setup-terraform@v3