name: Mixed Actions Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
      - uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09  # v5.0.0
      - uses: suspicious/action@v1
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd  # v3.1.2